fix: rebuild when check_rebuild fails (#5)
* check_rebuild now returns exit-status 0 when rebuild should NOT occur and 1 when it should. That ensures all internal errors trigger rebuild

* `list_file_diff` errors are now caught gracefully, an error is printed, and then `check_rebuild` returns nonzero exit-status to trigger rebuild.

diff --git a/scripts/check_rebuild b/scripts/check_rebuild
--- a/scripts/check_rebuild
+++ b/scripts/check_rebuild
@@ -1,18 +1,19 @@
 #!/bin/bash
-# Succeeds if any files matching the rebuild patterns, have changed since the base commit.
+# Fails if any files matching the rebuild patterns, have changed since the base commit.
+# If this script fails (nonzero exit), then the caller should rebuild.
 # The rebuild patterns are taken from the build manifest (computed from set of dependencies).
 set -euo pipefail
 
 BASE_COMMIT=$1
 REPOSITORY=$2
 
-# If given nothing, then return true to rebuild.
-[ -n "$BASE_COMMIT" ] || exit 0
+# If given nothing, then exit with failure to rebuild
+[ -n "$BASE_COMMIT" ] || exit 1
 
-# If a tainted tag exists, remove it and return true to rebuild.
+# If a tainted tag exists, remove it exit with failure to rebuild.
 if image_exists $REPOSITORY tainted; then
   echo "$REPOSITORY has been tainted. Will rebuild."
-  exit 0
+  exit 1
 fi
 
 # Compute .rebuild_patterns from the build manifest.
@@ -23,8 +24,16 @@ cat .rebuild_patterns
 
 git config diff.renameLimit 999999
 
-if list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | grep -f .rebuild_patterns &>/dev/null; then
-  exit 0
-else
+# Get list of files that differ
+different_files=$(list_file_diff ${BASE_COMMIT} ${COMMIT_HASH}) || {
+  echo "list_file_diff failed. Rebuild required.";
+  exit 1;
+}
+
+if grep -f .rebuild_patterns <<< "$different_files" &> /dev/null; then
+  echo "Rebuild required."
   exit 1
+else
+  echo "No rebuild required."
+  exit 0
 fi
