debug

diff --git a/scripts/check_rebuild b/scripts/check_rebuild
--- a/scripts/check_rebuild
+++ b/scripts/check_rebuild
@@ -29,9 +29,16 @@ echo "list_file_diff ${BASE_COMMIT} ${COMMIT_HASH}"
 cat `which list_file_diff`
 
 echo "list_file_diff output:"
-list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} || echo "list_file_diff failed."
+# run list_file_diff, but make sure output goes to console and is also captured in a variable
+# use a tee and a temp file to do this
+# if list_file_diff fails, exit with failure
+temp_diff_file=$(mktemp)
+{list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | tee temp_diff_file; } || { echo "list_file_diff failed"; exit 1; }
+different_files=$(cat "$temp_diff_file")
+rm "$temp_diff_file"
 
-if list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | grep -f .rebuild_patterns; then
+
+if grep -f .rebuild_patterns <<< "$different_files" &> /dev/null; then
   echo "Rebuild required."
   exit 1
 else
