debug

diff --git a/scripts/check_rebuild b/scripts/check_rebuild
--- a/scripts/check_rebuild
+++ b/scripts/check_rebuild
@@ -29,7 +29,7 @@ echo "list_file_diff ${BASE_COMMIT} ${COMMIT_HASH}"
 cat `which list_file_diff`
 
 echo "list_file_diff output:"
-list_file_diff ${BASE_COMMIT} ${COMMIT_HASH}
+list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} || echo "list_file_diff failed."
 
 if list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | grep -f .rebuild_patterns; then
   echo "Rebuild required."
