debug

diff --git a/scripts/check_rebuild b/scripts/check_rebuild
--- a/scripts/check_rebuild
+++ b/scripts/check_rebuild
@@ -7,10 +7,10 @@ set -euo pipefail
 BASE_COMMIT=$1
 REPOSITORY=$2
 
-# If given nothing, then return true to rebuild.
-[ -n "$BASE_COMMIT" ] || exit 0
+# If given nothing, then exit with failure to rebuild
+[ -n "$BASE_COMMIT" ] || exit 1
 
-# If a tainted tag exists, remove it and return true to rebuild.
+# If a tainted tag exists, remove it exit with failure to rebuild.
 if image_exists $REPOSITORY tainted; then
   echo "$REPOSITORY has been tainted. Will rebuild."
   exit 1
@@ -33,9 +33,14 @@ echo "list_file_diff output:"
 # use a tee and a temp file to do this
 # if list_file_diff fails, exit with failure
 temp_diff_file=$(mktemp)
-{ list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | tee "$temp_diff_file"; } || { echo "list_file_diff failed"; exit 1; }
-different_files=$(cat "$temp_diff_file")
-rm "$temp_diff_file"
+{
+  list_file_diff ${BASE_COMMIT} ${COMMIT_HASH} | tee "$temp_diff_file";
+} || {
+  rm -f "$temp_diff_file";
+  echo "list_file_diff failed. Rebuild required";
+  exit 1;
+}
+different_files=$(cat "$temp_diff_file") && rm "$temp_diff_file"
 
 
 if grep -f .rebuild_patterns <<< "$different_files" &> /dev/null; then
